### ISSUE TITLE
timelapse

### ISSUE THREAD

**Issue by bderembl** [Staacks/phyphox-android#14]
I was wondering if you were planing to add the camera in the list of sensors that you can control with phyphox.
It would be great to do timelapses or to be able to take pictures of an experiment at specific times.

thanks for the great app btw, it is really awesome

**Comment by Staacks** [comment]
Indeed, we plan to use the camera in phyphox. However, it is supposed to become a data source in the sense that it can provide brightness information, color values etc. which can be plotted. We do not have plans to directly save and share images or image sequences, which seems more like a documentation than a data acquisition feature. At least at the moment we decidedly focus on the latter. Still, you might be able to get the images as a side-effect of storing the raw data, but at the moment we are at a very early stage of planning on how the camera is used.

**Comment by Staacks** [comment]
(To clarify: I closed this issue as we will not actively implement this particular feature, but it might still emerge as a side-effect of our other camera-developments).
