### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Staacks/phyphox-android#16]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Staacks** [comment]
Good point, we should do that. Not high priority but I will add it to my list.

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.

**Comment by Staacks** [comment]
Screenshots and metadata have just been added with https://github.com/Staacks/phyphox-android/commit/64e669d0103acbe209bc413ae06783007ae0095f.

If this works properly on the next release (soon), I only have to remember to run fastlane and my meta-data-injection script once in a while.
