### ISSUE TITLE
Zoom for graphs

### ISSUE THREAD

**Issue by sfetzel** [Staacks/phyphox-android#2]
I have a feature request:
I'd like to see the details (small peaks) of a graph. For instance: double tapping on a graph displays it in fullscreen mode or: increase/decrease zoom using two fingers

**Comment by Staacks** [comment]
This is almost ready. A single tap on the graph switches to a full view of the graph, which can be panned (one finger) and zoomed (two fingers). If you are on Android, you can try it by joining our beta program (link at the bottom of https://phyphox.org/download/) or by building the dev-next branch. On iOS we will be ready soon...

**Comment by Staacks** [comment]
I will close this issue now. The function is now available as a beta test for Android and iOS and will make it to the official release version within a few weeks.
