### ISSUE TITLE
The control?cmd=... requests produce malformed Javascript object responses

### ISSUE THREAD

**Issue by scspaeth** [Staacks/phyphox-android#3]
The control?cmd=... requests produce malformed Javascript object responses. 
For example, the control?cmd=start returns {"result" = true}
The Firefox browser throws the error: 
SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 11 of the JSON data

https://github.com/Staacks/phyphox-android/blob/91074802276cf68fbdcc6899f88b8abd163bc2b9/app/src/main/java/de/rwth_aachen/phyphox/remoteServer.java#L731
The buggy version substitutes equal '=' for semicolon ':'

There are similar issues with lines: 735, 739, 755, 770, 773, ... 
A browser search for 
result\" = 
finds a total of 12 cases in this file.

**Comment by Staacks** [comment]
Thanks, I have just fixed it in the branch dev-next. This will be in the release in a few weeks.
